### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by jeFFeSS** [AlteredNadeo/op-wr-reporter#1]
Would you be willing to add a license to this repo please? I'm looking to adapt this for the Royal community to track records on the training maps. Thanks!

**Comment by akxcv** [comment]
Sure, added MIT as the license for this repo.

Though, if there's enough interest in expanding this functionality into more than just Altered Nadeo, I think it would be best to make a separate service that tracks records for all maps, and provides a webhook API to everyone (instead of making multiple plugins for specific maps/clubs)

**Comment by jeFFeSS** [comment]
Cheers for the code+license. A community plugin+service for realtime records would be great.
